### PR TITLE
Migrate Dirigible from Spring Boot 2.7.18 to 3.2.0

### PR DESCRIPTION
**Pull request by iliyan-velichkov**
Migrate Dirigible from Spring Boot 2.7.18 to 3.2.0
- depends on https://github.com/dirigiblelabs/olingo-odata2/pull/2

Execution comparison (master vs PR branch:

|Spring version| 2.7.18 | 3.2.0 |
|--|--|--|
| **build only** - `mvn clean install -D maven.test.skip=true -D skipTests -D maven.javadoc.skip=true -D license.skip=true`  | 21.8s | 21.6s |
| **parallel build only** - `mvn -T 1C clean install -D maven.test.skip=true -D skipTests -D maven.javadoc.skip=true -D license.skip=true` | 11s | 11s |
| **tests** - `mvn clean install -D maven.javadoc.skip=true -D license.skip=true` | 3.17 min | 03:05 min |
| **parallel tests** - `mvn -T 1C clean install -D maven.javadoc.skip=true -D license.skip=true` | 2.03 min | 01:51 min |
| **app start** - `java -jar build/application/target/dirigible-application-*-executable.jar` | 9.6s | 9.8s |

### CODE REVIEW

**Review by delchev — CHANGES_REQUESTED** [review]
OData does not work. Maybe the configuration in ODataConfig should be adapted as well?

**Review by delchev — CHANGES_REQUESTED** [review]
Please, doublecheck the usage of the following packages in *.java, *.js, *.mjs, *.ts files:
`javax.annotation.Nullable`
`javax.xml.soap`
`javax.servlet`
`javax.xml.transform`
`javax.xml.parsers`

**Comment by iliyan-velichkov** [comment]
> OData does not work. Maybe the configuration in ODataConfig should be adapted as well?

fixed

**Comment by iliyan-velichkov** [comment]
> `javax.xml.transform`
> `javax.xml.parsers`

done , except javax.xml.transform and javax.xml.parsers beause there is no jakarta alternative for them

**Review by delchev — APPROVED** [review]

**Comment by iliyan-velichkov** [comment]
@vmutafov did you have time to review this PR?

**Review by ThuF — APPROVED** [review]
+1 Seems good to me.

**Comment by iliyan-velichkov** [comment]
@vmutafov @delchev @ThuF can you ignore the CodeQL warning and merge the PR?

**Pull request merged**
