### PR TITLE
Refactor erroneous usage of http servlet response in the rest endpoints

### PR DESCRIPTION
**Pull request by g051051**
### What does this PR do?

changes how error responses are generated and returned by services.

### What issues does this PR fix or reference?

https://github.com/eclipse/dirigible/issues/188

### CODE REVIEW

**Comment by g051051** [comment]
I'm at a loss here.  I don't know what I'm doing wrong.  I'm signing off with my Eclipse email.  I can't tell what I'm doing differently from the first PR I raised.

**Comment by g051051** [comment]
OK, I sorted it out.  I did a rebase with edit, changed the author email, then force pushed to overwrite the bad commits.

**Review by ThuF — APPROVED** [review]

**Comment by ThuF** [comment]
Thanks, for creating the new PR! Maybe we'll have to update the contribution guide @delchev.

**Comment by g051051** [comment]
It was my inexperience with this aspect of GitHub that caused the problem, not the instructions.  It was instructive to figure out how to fix it.

**Pull request merged**
