### PR TITLE
Fix erroneous usage of http servlet response in the rest endpoints

### PR DESCRIPTION
**Pull request by g051051**
### What does this PR do?

Refactors the REST services error handling to eliminate some redundancy.

### What issues does this PR fix or reference?

188

### CODE REVIEW

**Review by ThuF — APPROVED** [review]
+1

**Comment by g051051** [comment]
Unfortunately I messed up something with the commit and can't quite figure out how to fix it (I messed up the sign-off).  Any idea on how to fix it?  I tried a rebase and reword on the commit, but it's still not happy.

**Comment by ThuF** [comment]
@g051051 Thank you for the pull request!

@delchev will have to double check the ECA status and what (if anything) else needs to be done, before merging it.

**Comment by ThuF** [comment]
> Unfortunately I messed up something with the commit and can't quite figure out how to fix it (I messed up the sign-off). Any idea on how to fix it? I tried a rebase and reword on the commit, but it's still not happy.

Thanks again, maybe the easiest way to workaround this will be to copy the whole repository content (with your changes) then reset to the master, paste the changes and create new PR 😄 As this will be quite an overhead, we'll briefly discuss it with @delchev tomorrow and merge it anyway 👍

**Comment by g051051** [comment]
It's actually not a big deal, I can redo the changes pretty quickly.  I'll do that and reopen the PR tomorrow.

**Pull request closed without merging**
