### PR TITLE
Add previous version of the entity to the event body on DAO update

### PR DESCRIPTION
**Pull request by iliyan-velichkov**

### CODE REVIEW

**Review by delchev — APPROVED** [review]

**Comment by ThuF** [comment]
I guess we can use `entity` and `entityUpdated`/`updatedEntity` instead, where the updated entity is the new one? Also `entityBeforeUpdate` and `entityAfterUpdate` seems fine to me.

**Comment by delchev** [comment]
```javascript
this.triggerEvent({
            operation: "update",
            table: "${tablePrefix}${dataName}",
            entity: entity,
            previous: previousEntity,
            key: {
```

can we use just **previous** for simplicity?

**Comment by ThuF** [comment]
### Here is few more options to consider as well

1. Using `previousEntity` and `entity`:
   ```typescript
   public update(entity: any): void {
       const previousEntity = this.findById(entity.Id);
       this.dao.update(entity);
       this.triggerEvent({
           operation: "update",
           table: "STUDENTS",
           entity: entity,
           previousEntity: previousEntity,
           key: 3
       });
   }
   ```

2. Using `currentEntity` and `priorEntity`:
   ```typescript
   public update(currentEntity: any): void {
       const priorEntity = this.findById(currentEntity.Id);
       this.dao.update(currentEntity);
       this.triggerEvent({
           operation: "update",
           table: "STUDENTS",
           currentEntity: currentEntity,
           priorEntity: priorEntity,
           key: 3
       });
   }
   ```

3. Using `updatedEntity` and `originalEntity`:
   ```typescript
   public update(updatedEntity: any): void {
       const originalEntity = this.findById(updatedEntity.Id);
       this.dao.update(updatedEntity);
       this.triggerEvent({
           operation: "update",
           table: "STUDENTS",
           updatedEntity: updatedEntity,
           originalEntity: originalEntity,
           key: 3
       });
   }
   ```

4. Using `newData` and `oldData`:
   ```typescript
   public update(newData: any): void {
       const oldData = this.findById(newData.Id);
       this.dao.update(newData);
       this.triggerEvent({
           operation: "update",
           table: "STUDENTS",
           newData: newData,
           oldData: oldData,
           key: 3
       });
   }
   ```

5. Using `previous` and `entity`:
   ```typescript
   public update(entity: any): void {
       const previous = this.findById(entity.Id);
       this.dao.update(entity);
       this.triggerEvent({
           operation: "update",
           table: "STUDENTS",
           entity: entity,
           previous: previous,
           key: 3
       });
   }
   ```

6. Using `entityBeforeUpdate` and `entityAfterUpdate`:
   ```typescript
   public update(entity: any): void {
       const entityBeforeUpdate = this.findById(entity.Id);
       this.dao.update(entity);
       this.triggerEvent({
           operation: "update",
           table: "STUDENTS",
           entityBeforeUpdate: entityBeforeUpdate,
           entityAfterUpdate: entity,
           key: 3
       });
   }
   ```
7. Using `entity` and `entityUpdated`:

   ```typescript
   public update(entity: any): void {
       const entityBeforeUpdate = this.findById(entity.Id);
       this.dao.update(entity);
       this.triggerEvent({
           operation: "update",
           table: "STUDENTS",
           entity: entityBeforeUpdate,
           entityUpdated: entity,
           key: 3
       });
   }
   ```

### Asking AI to compare the options

1. Using `previousEntity` and `entity`: Clear, but `previousEntity` might be slightly ambiguous.
2. Using `currentEntity` and `priorEntity`: Clear and descriptive, but `priorEntity` might be less intuitive than `previousEntity`.
3. Using `updatedEntity` and `originalEntity`: Clear and descriptive, but `originalEntity` might imply a static or unmodified state rather than the state before the update.
4. Using `newData` and `oldData`: Clear and concise, but `newData` and `oldData` might be less conventional when referring to entities in a database context.
5. Using `previous` and `entity`: Concise, but `previous` might be slightly ambiguous.
6. Using `entityBeforeUpdate` and `entityAfterUpdate`: Descriptive and explicit, providing clear indication of the states before and after the update.
7. Using `entity` and `entityUpdated`: Clear and concise, but `entityUpdated` might imply that `entity` represents the updated state.

_Considering **clarity**, **conciseness**, and **expressiveness**, **option 6** (`entityBeforeUpdate` and `entityAfterUpdate`) stands out. It provides explicit naming for both the state before and after the update, making the code very readable and understandable._

> _Therefore, I would recommend choosing option 6. It strikes a good balance between clarity and conciseness._

**Comment by ThuF** [comment]
Btw do we always want to fetch the previous entity? This would result into two SQL queries being executed with each call to the update method?

**Comment by iliyan-velichkov** [comment]
> Btw do we always want to fetch the previous entity? This would result into two SQL queries being executed with each call to the update method?

we discussed this on the scrum and we decided to always fetch it

**Comment by iliyan-velichkov** [comment]
> ### Here is few more options to consider as well
> 1. Using `previousEntity` and `entity`:
>    ```ts
>    public update(entity: any): void {
>        const previousEntity = this.findById(entity.Id);
>        this.dao.update(entity);
>        this.triggerEvent({
>            operation: "update",
>            table: "STUDENTS",
>            entity: entity,
>            previousEntity: previousEntity,
>            key: 3
>        });
>    }
>    ```
> 2. Using `currentEntity` and `priorEntity`:
>    ```ts
>    public update(currentEntity: any): void {
>        const priorEntity = this.findById(currentEntity.Id);
>        this.dao.update(currentEntity);
>        this.triggerEvent({
>            operation: "update",
>            table: "STUDENTS",
>            currentEntity: currentEntity,
>            priorEntity: priorEntity,
>            key: 3
>        });
>    }
>    ```
> 3. Using `updatedEntity` and `originalEntity`:
>    ```ts
>    public update(updatedEntity: any): void {
>        const originalEntity = this.findById(updatedEntity.Id);
>        this.dao.update(updatedEntity);
>        this.triggerEvent({
>            operation: "update",
>            table: "STUDENTS",
>            updatedEntity: updatedEntity,
>            originalEntity: originalEntity,
>            key: 3
>        });
>    }
>    ```
> 4. Using `newData` and `oldData`:
>    ```ts
>    public update(newData: any): void {
>        const oldData = this.findById(newData.Id);
>        this.dao.update(newData);
>        this.triggerEvent({
>            operation: "update",
>            table: "STUDENTS",
>            newData: newData,
>            oldData: oldData,
>            key: 3
>        });
>    }
>    ```
> 5. Using `previous` and `entity`:
>    ```ts
>    public update(entity: any): void {
>        const previous = this.findById(entity.Id);
>        this.dao.update(entity);
>        this.triggerEvent({
>            operation: "update",
>            table: "STUDENTS",
>            entity: entity,
>            previous: previous,
>            key: 3
>        });
>    }
>    ```
> 6. Using `entityBeforeUpdate` and `entityAfterUpdate`:
>    ```ts
>    public update(entity: any): void {
>        const entityBeforeUpdate = this.findById(entity.Id);
>        this.dao.update(entity);
>        this.triggerEvent({
>            operation: "update",
>            table: "STUDENTS",
>            entityBeforeUpdate: entityBeforeUpdate,
>            entityAfterUpdate: entity,
>            key: 3
>        });
>    }
>    ```
> 7. Using `entity` and `entityUpdated`:
>    ```ts
>    public update(entity: any): void {
>        const entityBeforeUpdate = this.findById(entity.Id);
>        this.dao.update(entity);
>        this.triggerEvent({
>            operation: "update",
>            table: "STUDENTS",
>            entity: entityBeforeUpdate,
>            entityUpdated: entity,
>            key: 3
>        });
>    }
>    ```
> 
> ### Asking AI to compare the options
> 1. Using `previousEntity` and `entity`: Clear, but `previousEntity` might be slightly ambiguous.
> 2. Using `currentEntity` and `priorEntity`: Clear and descriptive, but `priorEntity` might be less intuitive than `previousEntity`.
> 3. Using `updatedEntity` and `originalEntity`: Clear and descriptive, but `originalEntity` might imply a static or unmodified state rather than the state before the update.
> 4. Using `newData` and `oldData`: Clear and concise, but `newData` and `oldData` might be less conventional when referring to entities in a database context.
> 5. Using `previous` and `entity`: Concise, but `previous` might be slightly ambiguous.
> 6. Using `entityBeforeUpdate` and `entityAfterUpdate`: Descriptive and explicit, providing clear indication of the states before and after the update.
> 7. Using `entity` and `entityUpdated`: Clear and concise, but `entityUpdated` might imply that `entity` represents the updated state.
> 
> _Considering **clarity**, **conciseness**, and **expressiveness**, **option 6** (`entityBeforeUpdate` and `entityAfterUpdate`) stands out. It provides explicit naming for both the state before and after the update, making the code very readable and understandable._
> 
> > _Therefore, I would recommend choosing option 6. It strikes a good balance between clarity and conciseness._

I agree with the AI `entityBeforeUpdate` and `entityAfterUpdate ` are most descriptive. A bit long but descriptive. However, this way the interface for the update will be a lot more different than the others since`entity` is used for the others (delete, create).
We may consider to refactor it as well but keep in mind that this is incompatible change of the interface.

**Pull request merged**
