### PR TITLE
Dependencies from springboot

### PR DESCRIPTION
**Pull request by iliyan-velichkov**
- use spring managed dependencies to benefit from the compatibility
- add dirigible dependencies as managed to
  - remove versions declarations
  - enable using dirigible parent as parent of your project
  - using dirigible parent as pom import
- remove unused properties

### CODE REVIEW

**Comment by iliyan-velichkov** [comment]
@ThuF @vmutafov @delchev the PR is for review

**Comment by ThuF** [comment]
@iliyan-velichkov could you double check if setting a new version (e.g. as in the Release action) works as expected? Also could you check if the correct version is displayed in the `About` view?

**Comment by iliyan-velichkov** [comment]
> @iliyan-velichkov could you double check if setting a new version (e.g. as in the Release action) works as expected? Also could you check if the correct version is displayed in the `About` view?

here is the "About", I think it is fine
image

**Comment by iliyan-velichkov** [comment]
> @iliyan-velichkov could you double check if setting a new version (e.g. as in the Release action) works as expected? Also could you check if the correct version is displayed in the `About` view?

`mvn versions:set -DnewVersion=10.0.0` works as well

**Comment by iliyan-velichkov** [comment]
> It would be hard to maintain the correct list of all Dirigible dependencies in the main `pom.xml`.
> 
> I guess it would be better to leave this improvement for another time, after we introduce "groups" of maven dependencies e.g. `dirigible-components`.
> 
> Also could you create an issue about it and an example, how this improvement can be used in a custom dirigible stacks. Something similar to https://www.dirigible.io/help/tutorials/customizations/custom-stack/ (note that this is tutorial is working with version 6.x).

regarding the documentation, I will create such an example once the PR is merged

@ThuF why do you think that maintenance is tough? I even think that this way, the management is easier. You just put the dependencies which are need in the `dependencyManagement`. I think the pros are more than cons + this is a standard approach for dependencies management. This is what spring boot does.
Having in mind that the PR is ready, I think it is better to merge it and refactor it once these groups are implemented.
+ It will be easier to create a dirigible custom stack and the approach will be the same as you should use with Spring Boot.

**Comment by iliyan-velichkov** [comment]
created a separate PR - https://github.com/eclipse/dirigible/pull/3071

**Pull request closed without merging**
